apply plugin: 'com.android.application'

android {
    compileSdk = 37

    defaultConfig {
        applicationId ="com.example.android.opengl30"
        minSdk = 32
        targetSdk = 37
        versionCode =1
        versionName ="1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace ='com.example.android.opengl30'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation("com.google.android.material:material:1.14.0")
    implementation("androidx.activity:activity:1.13.0")
}
